name: Deployment

concurrency: deploy

on:
  push:
    branches:
      - develop

permissions:
  checks: write
  contents: write
  deployments: write

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Deploy
        run: sh deploy.sh
