name: Deployment

concurrency: deploy

on:
  push:
    branches:
      - develop

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
      - run: npm ci

      - name: Deploy
        run: sh deploy.sh