name: Deployment

concurrency: deploy

on:
  push:
    branches:
      - develop

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: sh deploy.sh