name: Deployment

concurrency: deploy

on:
  push:
    branches:
      - develop

permissions:
  checks: write
  contents: write
  deployments: write

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install dependencies
        run: npm ci

      - name: setup git config
        run: |
          git config --global user.name "Xinecraft"
          git config --global user.email "<kinnngg786@gmail.com>"

      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/

      - name: Deploy
        run: sh deploy.sh
