name: Deployment

concurrency: deploy

on:
  push:
    branches:
      - develop

permissions:
  checks: write
  contents: write
  deployments: write

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: npm ci

      - name: setup git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "<41898282+github-actions[bot]@users.noreply.github.com>"

      - name: Deploy
        run: sh deploy.sh
